apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  namespace: sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app

  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: sample-app-container
          image: girimausam/sample-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000